"""add null to approval status

Revision ID: d9db1cd17860
Revises: 
Create Date: 2020-10-01 22:35:24.385541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9db1cd17860'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'productname',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    op.alter_column('products', 'productspoilt',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'status',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    op.drop_constraint('products_productname_key', 'products', type_='unique')
    op.drop_constraint('products_productspoilt_key', 'products', type_='unique')
    op.drop_constraint('products_status_key', 'products', type_='unique')
    op.alter_column('supplyrequest', 'productname',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    op.drop_constraint('supplyrequest_approval_status_key', 'supplyrequest', type_='unique')
    op.drop_constraint('supplyrequest_productname_key', 'supplyrequest', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('supplyrequest_productname_key', 'supplyrequest', ['productname'])
    op.create_unique_constraint('supplyrequest_approval_status_key', 'supplyrequest', ['approval_status'])
    op.alter_column('supplyrequest', 'productname',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
    op.create_unique_constraint('products_status_key', 'products', ['status'])
    op.create_unique_constraint('products_productspoilt_key', 'products', ['productspoilt'])
    op.create_unique_constraint('products_productname_key', 'products', ['productname'])
    op.alter_column('products', 'status',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
    op.alter_column('products', 'productspoilt',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'productname',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
    # ### end Alembic commands ###
