"""edited products table

Revision ID: f64a0fd9e207
Revises: d9db1cd17860
Create Date: 2020-10-02 11:58:24.454698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f64a0fd9e207'
down_revision = 'd9db1cd17860'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('products_quantity_key', 'products', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('products_quantity_key', 'products', ['quantity'])
    op.alter_column('products', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
